# Generated by Django 4.0.4 on 2022-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_encouragements'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topics_read',
            field=models.ManyToManyField(blank=True, default=None, to='blog.topics'),
        ),
    ]
