# Generated by Django 4.0.4 on 2022-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_about_me_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='assets/imgs/users/'),
        ),
    ]
