# Generated by Django 4.0.4 on 2022-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='started_reading',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
