# Generated by Django 4.0.4 on 2022-06-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_started_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_pic.png', upload_to='profile_pics/'),
        ),
    ]
