# Generated by Django 4.0.4 on 2022-06-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encouragements',
        ),
    ]
